const examples = [
  ['Inventory', 'What products are running low?', 'LOW_STOCK', ['inventory'], 'Find stock at or below its threshold.', 'I do not have inventory levels connected yet.'],
  ['Inventory', 'What do I need to restock?', 'RESTOCK_RECOMMENDATION', ['inventory', 'sales'], 'Prioritise low stock and fast sellers.', 'I need inventory and recent sales data before recommending a restock.'],
  ['Inventory', 'Which products are almost finished?', 'LOW_STOCK', ['inventory'], 'Find the lowest stock items.', 'I do not have inventory levels connected yet.'],
  ['Inventory', 'Which products are overstocked?', 'OVERSTOCK', ['inventory'], 'Find stock materially above its target.', 'Overstock data is not available yet.'],
  ['Inventory', 'Which products have not sold recently?', 'DEAD_STOCK', ['inventory', 'sales'], 'Find products with no recent sale.', 'I need inventory and sales history to identify dead stock.'],
  ['Inventory', 'What products are close to expiry?', 'EXPIRY_TRACKING', ['inventory'], 'Sort connected expiry dates by proximity.', 'Expiry dates are not available yet.'],
  ['Inventory', 'How much stock do I have?', 'INVENTORY_SUMMARY', ['inventory'], 'Summarise connected stock quantities.', 'Inventory quantities are not available yet.'],
  ['Inventory', 'How many products are in stock?', 'INVENTORY_SUMMARY', ['inventory'], 'Count products with stock above zero.', 'Inventory quantities are not available yet.'],
  ['Inventory', 'Which products have the highest stock levels?', 'INVENTORY_SUMMARY', ['inventory'], 'Sort connected stock descending.', 'Inventory quantities are not available yet.'],
  ['Inventory', 'What stock should I check today?', 'INVENTORY_SUMMARY', ['inventory', 'expiry'], 'Prioritise low, expiring, or discrepant stock.', 'Inventory checks are not available yet.'],
  ['Sales', 'What were my sales today?', 'SALES_SUMMARY', ['sales'], 'Sum sales recorded today.', 'I do not have enough sales data yet to answer that.'],
  ['Sales', 'How much did I sell today?', 'SALES_SUMMARY', ['sales'], 'Sum today\'s recorded sale totals.', 'I do not have enough sales data yet to answer that.'],
  ['Sales', 'How much did I make this week?', 'SALES_SUMMARY', ['sales'], 'Sum sales from the current week.', 'I do not have enough sales data yet to answer that.'],
  ['Sales', 'What are my best-selling products?', 'TOP_SELLERS', ['sales', 'sale_items'], 'Rank products by units sold.', 'Product-level sales data is not available yet.'],
  ['Sales', 'What product sells the most?', 'TOP_SELLERS', ['sales', 'sale_items'], 'Return the highest unit seller.', 'Product-level sales data is not available yet.'],
  ['Sales', 'What are my top 5 products?', 'TOP_SELLERS', ['sales', 'sale_items'], 'Rank the five highest unit sellers.', 'Product-level sales data is not available yet.'],
  ['Sales', 'What day do I make the most sales?', 'BUSIEST_DAYS', ['sales'], 'Group sales by day and compare totals.', 'I need more sales history before comparing days.'],
  ['Sales', 'Are my sales increasing?', 'SALES_TREND', ['sales'], 'Compare the latest period with the prior period.', 'I need more sales history before identifying a trend.'],
  ['Sales', 'Are my sales decreasing?', 'SALES_TREND', ['sales'], 'Compare the latest period with the prior period.', 'I need more sales history before identifying a trend.'],
  ['Sales', 'Which products are selling poorly?', 'BOTTOM_SELLERS', ['sales', 'sale_items'], 'Rank products by low unit sales.', 'Product-level sales data is not available yet.'],
  ['Profit', 'How much profit did I make today?', 'PROFIT_SUMMARY', ['sales', 'cost_prices'], 'Subtract cost from selling price for today\'s sales.', 'Cost prices are not connected, so I cannot calculate profit yet.'],
  ['Profit', 'How much profit did I make this week?', 'PROFIT_SUMMARY', ['sales', 'cost_prices'], 'Calculate weekly gross profit.', 'Cost prices are not connected, so I cannot calculate profit yet.'],
  ['Profit', 'Which products make me the most profit?', 'TOP_PROFIT', ['sales', 'cost_prices'], 'Rank products by gross profit.', 'Cost prices are not connected, so I cannot calculate profit yet.'],
  ['Profit', 'Which products have the highest profit margin?', 'PROFIT_MARGIN', ['products', 'cost_prices'], 'Calculate profit divided by selling price.', 'Cost prices are not connected, so I cannot calculate margins yet.'],
  ['Profit', 'Which products are not profitable?', 'PROFIT_MARGIN', ['products', 'cost_prices'], 'Find products with zero or negative margin.', 'Cost prices are not connected, so I cannot calculate margins yet.'],
  ['Profit', 'Where am I making the most money?', 'TOP_PROFIT', ['sales', 'cost_prices'], 'Rank profit contribution by product.', 'Cost prices are not connected, so I cannot calculate profit yet.'],
  ['Credit', 'Who owes me money?', 'CUSTOMER_BALANCES', ['customers', 'credit'], 'List customers with positive balances.', 'There are no outstanding customer balances in the connected data.'],
  ['Credit', 'How much money is currently owed to me?', 'CUSTOMER_BALANCES', ['customers', 'credit'], 'Sum positive customer balances.', 'There are no outstanding customer balances in the connected data.'],
  ['Credit', 'Who has overdue credit?', 'OVERDUE_CREDIT', ['customers', 'credit'], 'List positive balances past their due date.', 'There are no overdue balances in the connected data.'],
  ['Credit', 'Which customers have not paid?', 'OVERDUE_CREDIT', ['customers', 'credit'], 'Find customers with overdue positive balances.', 'There are no overdue balances in the connected data.'],
  ['Credit', 'Who owes the most?', 'LARGEST_BALANCE', ['customers', 'credit'], 'Return the largest positive balance.', 'There are no outstanding customer balances in the connected data.'],
  ['Credit', 'Which customers usually pay on time?', 'RELIABILITY', ['customers', 'credit'], 'Use repayment history to rank reliability.', 'Customer repayment history is not available yet.'],
  ['Credit', 'How much credit did I give this month?', 'CREDIT_GIVEN', ['credit'], 'Sum positive credit transactions this month.', 'Credit transaction history is not available yet.'],
  ['Credit', 'Should I remind customers about their balances?', 'OVERDUE_CREDIT', ['customers', 'credit'], 'Highlight overdue balances for follow-up.', 'I do not have overdue balance data to make that recommendation.'],
  ['Restocking', 'What should I restock today?', 'RESTOCK_RECOMMENDATION', ['inventory', 'sales'], 'Combine low stock with sales velocity.', 'I need inventory and recent sales data before recommending a restock.'],
  ['Restocking', 'What products should I order more of?', 'RESTOCK_RECOMMENDATION', ['inventory', 'sales'], 'Prioritise products below minimum stock and selling quickly.', 'I need inventory and recent sales data before recommending a restock.'],
  ['Restocking', 'How much stock should I buy?', 'RESTOCK_QUANTITY', ['inventory', 'sales'], 'Estimate order quantity from stock and demand.', 'I need stock levels and demand history before estimating an order.'],
  ['Restocking', 'What should I prepare for the weekend?', 'DEMAND_FORECAST', ['sales_history'], 'Forecast weekend demand from sufficient history.', 'I need more historical sales data before I can make a reliable forecast.'],
  ['Dead stock', 'Show me my dead stock.', 'DEAD_STOCK', ['inventory', 'sales'], 'Find stock with no sales over the selected period.', 'I need inventory and sales history to identify dead stock.'],
  ['Dead stock', 'What stock is just sitting there?', 'DEAD_STOCK', ['inventory', 'sales'], 'Find items without recent movement.', 'I need inventory and sales history to identify dead stock.'],
  ['Expiry', 'Which products expire this week?', 'EXPIRY_TRACKING', ['inventory'], 'Filter expiry dates through the end of the week.', 'Expiry dates are not available yet.'],
  ['Cash flow', 'How much cash came into the business?', 'CASH_FLOW', ['sales', 'expenses'], 'Sum cash inflows and subtract connected outflows.', 'Expense data is not connected, so cash flow is not available yet.'],
  ['Cash flow', 'Am I spending more than I am making?', 'CASH_FLOW', ['sales', 'expenses'], 'Compare recorded inflows with expenses.', 'Expense data is not connected, so I cannot compare spending and income.'],
  ['Performance', 'How is my business doing?', 'BUSINESS_PERFORMANCE', ['sales', 'credit', 'inventory'], 'Combine sales, credit, and inventory signals.', 'I can summarise credit, but sales and inventory data are not sufficient yet.'],
  ['Performance', 'What should I focus on today?', 'BUSINESS_ADVICE', ['sales', 'credit', 'inventory'], 'Choose the most urgent supported business action.', 'I need more connected business data before making a data-based recommendation.'],
  ['Forecasting', 'What will probably sell next week?', 'DEMAND_FORECAST', ['sales_history'], 'Forecast only with sufficient historical sales.', 'I need more historical sales data before I can make a reliable forecast.'],
  ['Suppliers', 'Which supplier is cheapest?', 'SUPPLIER_COMPARISON', ['suppliers', 'prices'], 'Compare current supplier prices.', 'Supplier and purchase price data are not connected yet.'],
  ['Shrinkage', 'Am I losing stock?', 'STOCK_SHRINKAGE', ['inventory', 'stock_movements'], 'Compare expected stock with recorded movements.', 'Stock movement data is not connected yet.'],
  ['Analytics', 'Give me insights from my dashboard.', 'BUSINESS_PERFORMANCE', ['sales', 'credit', 'inventory'], 'Summarise the strongest supported signals.', 'I need more connected business data before generating dashboard insights.'],
  ['Advice', 'Give me 3 recommendations based on my current data.', 'BUSINESS_ADVICE', ['sales', 'credit', 'inventory'], 'Return up to three actions supported by available data.', 'I need more connected business data before making recommendations.'],
];

export const INTENT_CATALOG = examples.map(([category, question, intent, requiredData, responseLogic, exampleResponse]) => ({
  category,
  question,
  intent,
  requiredData,
  responseLogic,
  exampleResponse,
}));

export const SUGGESTED_QUESTIONS = [
  'Who owes me money?',
  'Who has overdue credit?',
  'How much did I sell today?',
  'What are my best-selling products?',
  'What should I restock?',
  'How is my business doing?',
];

export const INTENT_KEYWORDS = {
  CUSTOMER_BALANCES: ['owe', 'owed', 'balance', 'debt'],
  OVERDUE_CREDIT: ['overdue', 'late', 'not paid', 'remind'],
  LARGEST_BALANCE: ['owes the most', 'largest balance', 'highest balance'],
  CREDIT_GIVEN: ['credit did i give', 'credit this month'],
  SALES_SUMMARY: ['sales today', 'sold today', 'sales this week', 'made this week'],
  TOP_SELLERS: ['best-selling', 'best selling', 'best sellers', 'best seller', 'best sales', 'best products', 'top sellers', 'top seller', 'top products', 'most sales', 'sells the most', 'top 5'],
  BOTTOM_SELLERS: ['selling poorly', 'worst-selling', 'worst selling'],
  PROFIT_SUMMARY: ['profit today', 'profit this week', 'profit this month'],
  RESTOCK_RECOMMENDATION: ['restock', 'order more', 'buy tomorrow', 'buy more'],
  DEAD_STOCK: ['dead stock', 'not sold', 'sitting there', 'stop ordering'],
  EXPIRY_TRACKING: ['expiry', 'expire', 'expiring'],
  DEMAND_FORECAST: ['forecast', 'probably sell', 'expected to sell', 'prepare for the weekend'],
  CASH_FLOW: ['cash flow', 'spending more', 'cash came', 'money going'],
  BUSINESS_PERFORMANCE: ['how is my business', 'performing', 'business summary', 'dashboard insights'],
  BUSINESS_ADVICE: ['what should i focus', 'recommendations', 'improve', 'what should i do'],
  LOW_STOCK: ['running low', 'almost finished', 'low stock'],
  SUPPLIER_COMPARISON: ['supplier', 'cheapest', 'best price'],
  STOCK_SHRINKAGE: ['losing stock', 'stock disappearing', 'stock discrepancy'],
};
